---
provisioner:
  inventory:
    host_vars:
      instance-ubi9:
        activemq_federations:
          - name: amq-federation
            upstreams:
              - name: instance-ubi10
                user: amq-broker
                password: amq-broker
                static_connectors:
                  - instance-ubi10
            queue_policies:
              - name: TEST
                includes:
                  - queue_match: TEST
                    address_match: TEST
      instance-ubi10:
        activemq_federations:
          - name: amq-federation
            upstreams:
              - name: instance-ubi9
                user: amq-broker
                password: amq-broker
                static_connectors:
                  - instance-ubi9
            queue_policies:
              - name: TEST
                includes:
                  - queue_match: TEST
                    address_match: TEST
