---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
      vars:
        assets:
          - "{{ assets_server }}/amq/broker/7.9.4/amq-broker-7.9.4-bin.zip"
          - "{{ assets_server }}/amq/broker/7.10.0/amq-broker-7.10.0-bin.zip"
  roles:
    - activemq
