---
- name: Prepare
  hosts: all
  pre_tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
  tasks:
    - name: Include role for broker install
      ansible.builtin.include_role:
        name: activemq
      vars:
        activemq_version: "{{ '7.9.4' if amq_broker_enable is defined and amq_broker_enable else '2.18.0' }}"
