---
namespace: middleware_automation
name: amq
version: "2.2.8"
readme: README.md
authors:
  - Guido Grazioli <ggraziol@redhat.com>
description: Install and configure activemq / AMQ broker services.
license_file: "LICENSE"
tags:
  - broker
  - messaging
  - server
  - messagebus
  - infrastructure
  - runtimes
  - middleware
  - a4mw
dependencies:
  "middleware_automation.common": ">=1.1.0"
  "ansible.posix": ">=1.4.0"
repository: https://github.com/ansible-middleware/amq
documentation: https://ansible-middleware.github.io/amq
homepage: https://github.com/ansible-middleware/amq
issues: https://github.com/ansible-middleware/amq/issues
build_ignore:
  - .gitignore
  - .github
  - '*.tar.gz'
  - '*.zip'
  - molecule
  - changelogs
  - docs/_gh_include
  - docs/conf.py
  - docs/roles.rst.template
  - docs/requirements.yml
