---
- name: Display Ansible version
  ansible.builtin.debug:
    msg: "Ansible version is  {{ ansible_version.full }}"

- name: "Set package name for sudo"
  ansible.builtin.set_fact:
    sudo_pkg_name: 'sudo'

- name: "Ensure {{ sudo_pkg_name }} is installed (if user is root)."
  ansible.builtin.yum:
    name: "{{ sudo_pkg_name }}"
  retries: 3
  when:
    - ansible_user_id == 'root'

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: "Check if {{ sudo_pkg_name }} is installed."
  ansible.builtin.assert:
    that:
      - sudo_pkg_name in ansible_facts.packages