---
- import_playbook: ../prepare.yml

- name: Prepare schema validation
  hosts: all
  vars:
    temp_dir: "/tmp/amq_test"
  tasks:
    - name: "Setup: Create a fake installation directory"
      ansible.builtin.file:
        path: "{{ temp_dir }}/schema"
        state: directory
        mode: '0755'
      become: "{{ activemq_install_require_privileges_escalation | default(true) }}"

    - name: "Setup: Place the broken XSD file"
      ansible.builtin.copy:
       src: "activemq.xsd"
       dest: "{{ temp_dir }}/schema/activemq.xsd"
       owner: root
       group: root
       mode: '0644'
      become: "{{ activemq_install_require_privileges_escalation | default(true) }}"