---
- name: Converge
  hosts: all
  gather_facts: yes
  vars:
    activemq_ha_enabled: true
    activemq_disable_hornetq_protocol: true
    activemq_disable_mqtt_protocol: true
    activemq_disable_amqp_protocol: true
    activemq_disable_stomp_protocol: true
    activemq_shared_storage: true
    activemq_configure_firewalld: false  
    activemq_tls_enabled: True
    activemq_tls_keystore_path: nfs/identity.ks
    activemq_tls_keystore_pasword: changeme
    activemq_tls_truststore_path: nfs/trust.ks
    activemq_tls_truststore_password: changeit
    activemq_acceptors:
      - name: artemis
        bind_address: 0.0.0.0
        bind_port: "{{ activemq_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: CORE
          useEpoll: true
          sslEnabled: true
          keyStorePath: "{{ activemq_tls_keystore_dest }}"
          keyStorePassword: "{{ activemq_tls_keystore_pasword }}"
          trustStorePath: "{{ activemq_tls_truststore_dest }}"
          trustStorePassword: "{{ activemq_tls_truststore_password }}"
          verifyHost: False
    activemq_connectors:
      - name: artemis
        address: "{{ activemq_host }}"
        port: "{{ activemq_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: CORE
          useEpoll: true
          sslEnabled: true
          keyStorePath: "{{ activemq_tls_keystore_dest }}"
          keyStorePassword: "{{ activemq_tls_keystore_pasword }}"
          trustStorePath: "{{ activemq_tls_truststore_dest }}"
          trustStorePassword: "{{ activemq_tls_truststore_password }}"
          verifyHost: False
      - name: instance1
        address: instance1
        port: "{{ activemq_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: CORE
          useEpoll: true
          sslEnabled: true
          keyStorePath: "{{ activemq_tls_keystore_dest }}"
          keyStorePassword: "{{ activemq_tls_keystore_pasword }}"
          trustStorePath: "{{ activemq_tls_truststore_dest }}"
          trustStorePassword: "{{ activemq_tls_truststore_password }}"
          verifyHost: False
      - name: instance2
        address: instance2
        port: "{{ activemq_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: CORE
          useEpoll: true
          sslEnabled: true
          keyStorePath: "{{ activemq_tls_keystore_dest }}"
          keyStorePassword: "{{ activemq_tls_keystore_pasword }}"
          trustStorePath: "{{ activemq_tls_truststore_dest }}"
          trustStorePassword: "{{ activemq_tls_truststore_password }}"
          verifyHost: False
  collections:
    - middleware_automation.redhat_csp_download
  roles:
    - activemq
