---
platforms:
  - name: instance-ubi9
    image: registry.access.redhat.com/ubi9/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    systemd: always
    network: amq
    volumes:
      - nfs:/opt/amq/amq-broker/data/shared

  - name: instance-ubi10
    image: registry.access.redhat.com/ubi10/ubi-init:latest
    pre_build_image: true
    privileged: true
    command: "/usr/sbin/init"
    systemd: always
    network: amq
    volumes:
      - nfs:/opt/amq/amq-broker/data/shared

provisioner:
  inventory:
    host_vars:
      instance-ubi9:
        activemq_ha_role: 'primary'
        activemq_broker_connections:
          - uri: 'tcp://instance-ubi9:61616?sslEnabled=True;keyStorePath=/opt/amq/amq-broker/etc/identity.ks;keyStorePassword=securepass;trustStorePath=/opt/amq/amq-broker/etc/trust.ks;trustStorePassword=securepass;verifyHost=False'
            name: brokerA-2-brokerA
            user: amq-broker
            password: amq-broker
            operations:
              - type: sender
                parameters:
                  address_match: 'b.#'
              - type: receiver
                parameters:
                  address_match: 'a.#'
      instance-ubi10:
        activemq_ha_role: 'backup'
        activemq_ha_backup_failover_on_shutdown: true
