---
- name: Prepare
  hosts: all
  tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
    - name: "Create {{ activemq.service_name }} service user"
      become: yes
      ansible.builtin.user:
        name: amq-broker
        home: /opt/amq/
        system: yes
        create_home: no
    - name: Set ownership on nfs mounted parent
      ansible.builtin.file:
        path: /opt/amq/amq-broker/
        owner: amq-broker
        group: amq-broker
        mode: 0755
    - name: Install CA in shared truststore
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /usr/share/pki/ca-trust-source/anchors/
        owner: root
        group: root
        mode: 0444
      become: true
      loop:
        - "nfs/server-ca.crt"
    - name: Run update_ca_trust
      ansible.builtin.command: update-ca-trust
      changed_when: False
      become: true
