---
- name: Verify
  hosts: all
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check if amq-broker service is started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["amq-broker.service"]["state"] == "running"
          - ansible_facts.services["amq-broker.service"]["status"] == "enabled"

    - name: Read content of instance1 logs
      ansible.builtin.slurp:
        src: /var/log/activemq/amq-broker/artemis.log
      register: slurped_log_instance1
      delegate_to: instance1
      run_once: true

    - name: Read content of instance2 logs
      ansible.builtin.slurp:
        src: /var/log/activemq/amq-broker/artemis.log
      register: slurped_log_instance2
      delegate_to: instance2
      run_once: true

    - name: Check cluster status
      block:
        - name: Check master on instance1
          ansible.builtin.assert:
            that:
              - "'live Message Broker is starting' in slurped_log_instance1.content|b64decode"
              - "'Waiting indefinitely to obtain live lock' in slurped_log_instance1.content|b64decode"
              - "'Server is now live' in slurped_log.content|b64decode or 'Server is now active' in slurped_log.content|b64decode"
            quiet: true
        - name: Check slave on instance2
          ansible.builtin.assert:
            that:
              - "'backup Message Broker is starting' in slurped_log_instance2.content|b64decode"
              - "'Waiting to become backup node' in slurped_log_instance2.content|b64decode"
              - "'got backup lock' in slurped_log_instance2.content|b64decode"
              - "'waiting live to fail before it gets active' in slurped_log_instance2.content|b64decode"
            quiet: true
