---
provisioner:
  inventory:
    host_vars:
      instance-ubi9:
        activemq_broker_connections:
          - uri: "tcp://instance-ubi10:{{ activemq_port }}"
            name: DC2
            sync: true
            user: amq-broker
            password: amq-broker
            operations:
              - type: mirror
                parameters:
                  queue_removal: false
      instance-ubi10:
        activemq_broker_connections:
          - uri: "tcp://instance-ubi9:{{ activemq_port }}"
            name: DC1
            sync: true
            user: amq-broker
            password: amq-broker
            operations:
              - type: mirror
                parameters:
                  queue_removal: false
