---
- import_playbook: ../prepare.yml

- name: Prepare mirroring
  hosts: all
  tasks:
    - name: "Display value of activemq_install_requires_become"
      ansible.builtin.debug:
        var: activemq_install_requires_become
