---
- name: Verify
  hosts: all
  become: "{{ activemq_install_requires_become | default(true) }}"
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Populate activemq facts
      middleware_automation.amq.activemq_facts:
        base_url: http://localhost:8161
        auth_username: amq-broker
        auth_password: amq-broker
        validate_certs: false

    - name: Check if amq-broker service is started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["amq-broker.service"]["state"] == "running"
          - ansible_facts.services["amq-broker.service"]["status"] == "enabled"

    - name: Check cluster status via jolokia facts (instance1)
      ansible.builtin.assert:
        that:
          - ansible_facts.activemq.Active == true
          - ansible_facts.activemq.Backup == false
          - ansible_facts.activemq.Clustered == false
          - ansible_facts.activemq.SharedStore == false
          - ansible_facts.activemq.HAPolicy == "Primary Only"
      when: inventory_hostname == 'instance1'

    - name: Check cluster status via jolokia facts (instance2)
      ansible.builtin.assert:
        that:
          - ansible_facts.activemq.Active == true
          - ansible_facts.activemq.Backup == false
          - ansible_facts.activemq.Clustered == false
          - ansible_facts.activemq.SharedStore == false
          - ansible_facts.activemq.HAPolicy == "Primary Only"
      when: inventory_hostname == 'instance2'
