---
- name: Converge
  hosts: all
  gather_facts: yes
  environment:
    http_proxy: "{{ lookup('env', 'PROXY') }}"
    https_proxy: "{{ lookup('env', 'PROXY') }}"
    no_proxy: "{{ lookup('env', 'NO_PROXY') }}"
  module_defaults:
    ansible.builtin.get_url:
      validate_certs: "{{ not lookup('env', 'PROXY') != '' }}"
  vars:
    activemq_ha_enabled: true
    activemq_cluster_enabled: true
    activemq_cluster_discovery: static
    activemq_disable_hornetq_protocol: true
    activemq_disable_mqtt_protocol: true
    activemq_disable_amqp_protocol: true
    activemq_disable_stomp_protocol: true
    activemq_shared_storage: false
    activemq_replication: true
    activemq_ha_allow_failback: true
    activemq_configure_firewalld: false
    activemq_modular_configuration: true
    activemq_ha_check_for_active_server: true
    activemq_systemd_wait_for_port_number: 8161
    activemq_ha_quorum_size: 1
    activemq_ha_vote_on_replication_failure: true
    activemq_users:
    - user: amq
      password: amqbrokerpass
      roles: [ amq ]
    activemq_acceptors:
      - name: "{{ inventory_hostname }}"
        bind_address: 0.0.0.0
        bind_port: "{{ activemq_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: CORE,AMQP
          useEpoll: true
          sslEnabled: false
    activemq_connectors:
      - name: instance1
        address: instance1
        port: "{{ activemq_port }}"
      - name: instance2
        address: instance2
        port: "{{ activemq_port }}"
    activemq_addresses:
      - name: queue.in
        anycast:
          - name: queue.in
      - name: queue.out
        anycast:
          - name: queue.out
      - name: DLQ
        anycast:
          - name: DLQ
            parameters:
              durable: True
      - name: ExpiryQueue
        anycast:
          - name: ExpiryQueue
      - name: a.test
        anycast:
          - name: a.test
      - name: b.test
        anycast:
          - name: b.test
            parameters:
              max_consumers: 1
              delay_before_dispatch: 3
    activemq_diverts:
      - name: TESTDIVERT
        address: queue.in
        forwarding_address: queue.out
        routing_type: ANYCAST
        filter: "msgType LIKE '%ff%'"
        exclusive: True
  pre_tasks:
    - name: Set HA role for instance1
      ansible.builtin.set_fact:
        activemq_ha_role: 'primary'
      when: inventory_hostname == 'instance1'

    - name: Set HA role for instance2
      ansible.builtin.set_fact:
        activemq_ha_role: 'backup'
        activemq_replicated: true
      when: inventory_hostname == 'instance2'
  roles:
    - middleware_automation.amq.activemq
